-- https://school.programmers.co.kr/learn/courses/30/lessons/164673
SELECT
    b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID,
    r.CONTENTS, LEFT(r.CREATED_DATE, 10) AS CREATED_DATE
FROM USED_GOODS_BOARD AS b
    INNER JOIN USED_GOODS_REPLY AS r
ON r.BOARD_ID = b.BOARD_ID
WHERE LEFT(b.CREATED_DATE, 7) = '2022-10'
ORDER BY r.CREATED_DATE, b.TITLE